name: Run visual tests
on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  build:
    # Run this job on push to master when *not* publishing a tag
    # and on 'percy' labeled pull requests
    if: |
      (${{ github.event_name == 'push' }} && startsWith(github.ref, 'refs/tags/') != true) ||
      (${{ github.event_name == 'pull_request' }} && ${{ github.event.label.name == 'percy' }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: |
          echo "PERCY_TOKEN=${{ secrets.PERCY_TOKEN }}" > .env
          npx playwright install --with-deps chromium
          npm run test